export const ALL_STOCK_REQUEST = "ALL_STOCK_REQUEST";
export const ALL_STOCK_SUCCESS = "ALL_STOCK_SUCCESS";
export const ALL_STOCK_FAIL = "ALL_STOCK_FAIL";

export const STOCK_REGISTER_REQUEST = "STOCK_REGISTER_REQUEST";
export const STOCK_REGISTER_SUCCESS = "STOCK_REGISTER_SUCCESS";
export const STOCK_REGISTER_FAIL = "STOCK_REGISTER_FAIL";