export const ALL_STOCK_REQUEST = "ALL_STOCK_REQUEST";
export const ALL_STOCK_SUCCESS = "ALL_STOCK_SUCCESS";
export const ALL_STOCK_FAIL = "ALL_STOCK_FAIL";

export const STOCK_REQUEST = "STOCK_REQUEST";
export const STOCK_SUCCESS = "STOCK_SUCCESS";
export const STOCK_FAIL = "STOCK_FAIL";

export const STOCK_REGISTER_REQUEST = "STOCK_REGISTER_REQUEST";
export const STOCK_REGISTER_SUCCESS = "STOCK_REGISTER_SUCCESS";
export const STOCK_REGISTER_FAIL = "STOCK_REGISTER_FAIL";

export const STOCK_DELETE_REQUEST = "STOCK_DELETE_REQUEST";
export const STOCK_DELETE_SUCCESS = "STOCK_DELETE_SUCCESS";
export const STOCK_DELETE_FAIL = "STOCK_DELETE_FAIL";

export const STOCK_UPDATE_REQUEST = "STOCK_UPDATE_REQUEST";
export const STOCK_UPDATE_SUCCESS = "STOCK_UPDATE_SUCCESS";
export const STOCK_UPDATE_FAIL = "STOCK_UPDATE_FAIL";
export const STOCK_UPDATE_RESET = "STOCK_UPDATE_RESET"; 

export const STOCK_DETAILS_REQUEST = 'STOCK_DETAILS_REQUEST'
export const STOCK_DETAILS_SUCCESS = 'STOCK_DETAILS_SUCCESS'
export const STOCK_DETAILS_FAIL = 'STOCK_DETAILS_FAIL'