export const ALL_BRAND_REQUEST = "ALL_BRAND_REQUEST";
export const ALL_BRAND_SUCCESS = "ALL_BRAND_SUCCESS";
export const ALL_BRAND_FAIL = "ALL_BRAND_FAIL";

export const BRAND_REQUEST = "BRAND_REQUEST";
export const BRAND_SUCCESS = "BRAND_SUCCESS";
export const BRAND_FAIL = "BRAND_FAIL";

export const BRAND_REGISTER_REQUEST = "BRAND_REGISTER_REQUEST";
export const BRAND_REGISTER_SUCCESS = "BRAND_REGISTER_SUCCESS";
export const BRAND_REGISTER_FAIL = "BRAND_REGISTER_FAIL";

export const BRAND_DELETE_REQUEST = "BRAND_DELETE_REQUEST";
export const BRAND_DELETE_SUCCESS = "BRAND_DELETE_SUCCESS";
export const BRAND_DELETE_FAIL = "BRAND_DELETE_FAIL";

export const BRAND_UPDATE_REQUEST = "BRAND_UPDATE_REQUEST";
export const BRAND_UPDATE_SUCCESS = "BRAND_UPDATE_SUCCESS";
export const BRAND_UPDATE_FAIL = "BRAND_UPDATE_FAIL";
export const BRAND_UPDATE_RESET = "BRAND_UPDATE_RESET"; 