
export const ALL_SUPPLIER_LIST_REQUEST = "ALL_SUPPLIER_LIST_REQUEST";
export const ALL_SUPPLIER_LIST_SUCCESS = "ALL_SUPPLIER_LIST_SUCCESS";
export const ALL_SUPPLIER_LIST_FAIL = "ALL_SUPPLIER_LIST_FAIL";

export const SUPPLIER_LIST_REQUEST = "SUPPLIER_LIST_REQUEST";
export const SUPPLIER_LIST_SUCCESS = "SUPPLIER_LIST_SUCCESS";
export const SUPPLIER_LIST_FAIL = "SUPPLIER_LIST_FAIL";

export const SUPPLIER_REGISTER_REQUEST = "SUPPLIER_REGISTER_REQUEST";
export const SUPPLIER_REGISTER_SUCCESS = "SUPPLIER_REGISTER_SUCCESS";
export const SUPPLIER_REGISTER_FAIL = "SUPPLIER_REGISTER_FAIL";
export const SUPPLIER_REGISTER_RESET = "SUPPLIER_REGISTER_RESET";

export const SUPPLIER_DELETE_REQUEST = "SUPPLIER_DELETE_REQUEST";
export const SUPPLIER_DELETE_SUCCESS = "SUPPLIER_DELETE_SUCCESS";
export const SUPPLIER_DELETE_FAIL = "SUPPLIER_DELETE_FAIL";

export const SUPPLIER_UPDATE_REQUEST = "SUPPLIER_UPDATE_REQUEST";
export const SUPPLIER_UPDATE_SUCCESS = "SUPPLIER_UPDATE_SUCCESS";
export const SUPPLIER_UPDATE_FAIL = "SUPPLIER_UPDATE_FAIL";
export const SUPPLIER_UPDATE_RESET = "SUPPLIER_UPDATE_RESET"; 