export const ALL_PATIANT_LIST_REQUEST = "ALL_PATIANT_LIST_REQUEST";
export const ALL_PATIANT_LIST_SUCCESS = "ALL_PATIANT_LIST_SUCCESS";
export const ALL_PATIANT_LIST_FAIL = "ALL_PATIANT_LIST_FAIL";

export const PATIANT_LIST_REQUEST = "PATIANT_LIST_REQUEST";
export const PATIANT_LIST_SUCCESS = "PATIANT_LIST_SUCCESS";
export const PATIANT_LIST_FAIL = "PATIANT_LIST_FAIL";

export const PATIANT_REGISTER_REQUEST = "PATIANT_REGISTER_REQUEST";
export const PATIANT_REGISTER_SUCCESS = "PATIANT_REGISTER_SUCCESS";
export const PATIANT_REGISTER_FAIL = "PATIANT_REGISTER_FAIL";

export const PATIANT_DELETE_REQUEST = "PATIANT_DELETE_REQUEST";
export const PATIANT_DELETE_SUCCESS = "PATIANT_DELETE_SUCCESS";
export const PATIANT_DELETE_FAIL = "PATIANT_DELETE_FAIL";

export const PATIANT_UPDATE_REQUEST = "PATIANT_UPDATE_REQUEST";
export const PATIANT_UPDATE_SUCCESS = "PATIANT_UPDATE_SUCCESS";
export const PATIANT_UPDATE_FAIL = "PATIANT_UPDATE_FAIL";
export const PATIANT_UPDATE_RESET = "PATIANT_UPDATE_RESET"; 