export const PATIENT_TYPE_LIST_REQUEST = "PATIENT_TYPE_LIST_REQUEST";
export const PATIENT_TYPE_LIST_SUCCESS = "PATIENT_TYPE_LIST_SUCCESS";
export const PATIENT_TYPE_LIST_FAIL = "PATIENT_TYPE_LIST_FAIL";
