export const INVOICE_REGISTER_REQUEST = "INVOICE_REGISTER_REQUEST";
export const INVOICE_REGISTER_SUCCESS = "INVOICE_REGISTER_SUCCESS";
export const INVOICE_REGISTER_FAIL = "INVOICE_REGISTER_FAIL";

export const INVOICE_DETAILS_REQUEST = "INVOICE_REGISTER_REQUEST";
export const INVOICE_DETAILS_SUCCESS = "INVOICE_DETAILS_SUCCESS";
export const INVOICE_DETAILS_FAIL = "INVOICE_DETAILS_FAIL";
