export const ALL_DRUG_LIST_REQUEST = "ALL_DRUG_LIST_REQUEST";
export const ALL_DRUG_LIST_SUCCESS = "ALL_DRUG_LIST_SUCCESS";
export const ALL_DRUG_LIST_FAIL = "ALL_DRUG_LIST_FAIL";

export const DRUG_LIST_REQUEST = "DRUG_LIST_REQUEST";
export const DRUG_LIST_SUCCESS = "DRUG_LIST_SUCCESS";
export const DRUG_LIST_FAIL = "DRUG_LIST_FAIL";

export const DRUG_REGISTER_REQUEST = "DRUG_REGISTER_REQUEST";
export const DRUG_REGISTER_SUCCESS = "DRUG_REGISTER_SUCCESS";
export const DRUG_REGISTER_FAIL = "DRUG_REGISTER_FAIL";
export const DRUG_REGISTER_RESET = "DRUG_REGISTER_RESET";

export const DRUG_DELETE_REQUEST = "DRUG_DELETE_REQUEST";
export const DRUG_DELETE_SUCCESS = "DRUG_DELETE_SUCCESS";
export const DRUG_DELETE_FAIL = "DRUG_DELETE_FAIL";

export const DRUG_UPDATE_REQUEST = "DRUG_UPDATE_REQUEST";
export const DRUG_UPDATE_SUCCESS = "DRUG_UPDATE_SUCCESS";
export const DRUG_UPDATE_FAIL = "DRUG_UPDATE_FAIL";
export const DRUG_UPDATE_RESET = "DRUG_UPDATE_RESET";