export const ALL_DISEASE_REQUEST = "ALL_DISEASE_REQUEST";
export const ALL_DISEASE_SUCCESS = "ALL_DISEASE_SUCCESS";
export const ALL_DISEASE_FAIL = "ALL_DISEASE_FAIL";

export const DISEASE_REQUEST = "DISEASE_REQUEST";
export const DISEASE_SUCCESS = "DISEASE_SUCCESS";
export const DISEASE_FAIL = "DISEASE_FAIL";

export const DISEASE_REGISTER_REQUEST = "DISEASE_REGISTER_REQUEST";
export const DISEASE_REGISTER_SUCCESS = "DISEASE_REGISTER_SUCCESS";
export const DISEASE_REGISTER_FAIL = "DISEASE_REGISTER_FAIL";

export const DISEASE_DELETE_REQUEST = "DISEASE_DELETE_REQUEST";
export const DISEASE_DELETE_SUCCESS = "DISEASE_DELETE_SUCCESS";
export const DISEASE_DELETE_FAIL = "DISEASE_DELETE_FAIL";

export const DISEASE_UPDATE_REQUEST = "DISEASE_UPDATE_REQUEST";
export const DISEASE_UPDATE_SUCCESS = "DISEASE_UPDATE_SUCCESS";
export const DISEASE_UPDATE_FAIL = "DISEASE_UPDATE_FAIL";
export const DISEASE_UPDATE_RESET = "DISEASE_UPDATE_RESET"; 