export const ALL_ALERGY_REQUEST = "ALL_ALERGY_REQUEST";
export const ALL_ALERGY_SUCCESS = "ALL_ALERGY_SUCCESS";
export const ALL_ALERGY_FAIL = "ALL_ALERGY_FAIL";

export const ALERGY_REQUEST = "ALERGY_REQUEST";
export const ALERGY_SUCCESS = "ALERGY_SUCCESS";
export const ALERGY_FAIL = "ALERGY_FAIL";

export const ALERGY_REGISTER_REQUEST = "ALERGY_REGISTER_REQUEST";
export const ALERGY_REGISTER_SUCCESS = "ALERGY_REGISTER_SUCCESS";
export const ALERGY_REGISTER_FAIL = "ALERGY_REGISTER_FAIL";

export const ALERGY_DELETE_REQUEST = "ALERGY_DELETE_REQUEST";
export const ALERGY_DELETE_SUCCESS = "ALERGY_DELETE_SUCCESS";
export const ALERGY_DELETE_FAIL = "ALERGY_DELETE_FAIL";

export const ALERGY_UPDATE_REQUEST = "ALERGY_UPDATE_REQUEST";
export const ALERGY_UPDATE_SUCCESS = "ALERGY_UPDATE_SUCCESS";
export const ALERGY_UPDATE_FAIL = "ALERGY_UPDATE_FAIL";
export const ALERGY_UPDATE_RESET = "ALERGY_UPDATE_RESET"; 