export const TREATEMENT_TYPE_LIST_REQUEST = "TREATEMENT_TYPE_LIST_REQUEST";
export const TREATEMENT_TYPE_LIST_SUCCESS = "TREATEMENT_TYPE_LIST_SUCCESS";
export const TREATEMENT_TYPE_LIST_FAIL = "TREATEMENT_TYPE_LIST_FAIL";
