export const MASTER_REQUEST = "MASTER_REQUEST";
export const MASTER_SUCCESS = "MASTER_SUCCESS";
export const MASTER_FAIL = "MASTER_FAIL";

export const MASTER_UPDATE_REQUEST = "MASTER_UPDATE_REQUEST";
export const MASTER_UPDATE_SUCCESS = "MASTER_UPDATE_SUCCESS";
export const MASTER_UPDATE_FAIL = "MASTER_UPDATE_FAIL";
export const MASTER_UPDATE_RESET = "MASTER_UPDATE_RESET";
