export const ALL_TREATEMENT_LIST_REQUEST = "ALL_TREATEMENT_LIST_REQUEST";
export const ALL_TREATEMENT_LIST_SUCCESS = "ALL_TREATEMENT_LIST_SUCCESS";
export const ALL_TREATEMENT_LIST_FAIL = "ALL_TREATEMENT_LIST_FAIL";

export const TREATEMENT_LIST_REQUEST = "TREATEMENT_LIST_REQUEST";
export const TREATEMENT_LIST_SUCCESS = "TREATEMENT_LIST_SUCCESS";
export const TREATEMENT_LIST_FAIL = "TREATEMENT_LIST_FAIL";

export const TREATEMENT_REGISTER_REQUEST = "TREATEMENT_REGISTER_REQUEST";
export const TREATEMENT_REGISTER_SUCCESS = "TREATEMENT_REGISTER_SUCCESS";
export const TREATEMENT_REGISTER_FAIL = "TREATEMENT_REGISTER_FAIL";
export const TREATEMENT_REGISTER_RESET = "TREATEMENT_REGISTER_RESET";

export const TREATEMENT_DELETE_REQUEST = "TREATEMENT_DELETE_REQUEST";
export const TREATEMENT_DELETE_SUCCESS = "TREATEMENT_DELETE_SUCCESS";
export const TREATEMENT_DELETE_FAIL = "TREATEMENT_DELETE_FAIL";

export const TREATEMENT_UPDATE_REQUEST = "TREATEMENT_UPDATE_REQUEST";
export const TREATEMENT_UPDATE_SUCCESS = "TREATEMENT_UPDATE_SUCCESS";
export const TREATEMENT_UPDATE_FAIL = "TREATEMENT_UPDATE_FAIL";
export const TREATEMENT_UPDATE_RESET = "TREATEMENT_UPDATE_RESET";

export const TREATEMENT_DETAILS_REQUEST = 'TREATEMENT_DETAILS_REQUEST'
export const TREATEMENT_DETAILS_SUCCESS = 'TREATEMENT_DETAILS_SUCCESS'
export const TREATEMENT_DETAILS_FAIL = 'TREATEMENT_DETAILS_FAIL'
